services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./html:/var/www/html
      - ./nginx/logs:/var/log/nginx
      - ./nginx/scripts:/scripts
      - ./nginx/conf.d/letsencrypt:/etc/letsencrypt
      - ./nginx/logs/letsencrypt:/var/log/letsencrypt
    depends_on:
      - php
      - phpmyadmin
    entrypoint: bash /scripts/start.sh
    networks:
      - webnet

  php:
    build: ./php
    container_name: php
    volumes:
      - ./html:/var/www/html
    networks:
      - webnet

  mysql:
    image: mysql:5.6
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=saU76v#LmbT&bg5
      #- MYSQL_DATABASE=wap
      #- MYSQL_USER=wap
      #- MYSQL_PASSWORD=5.cPfw_TUROTAxKW
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - webnet

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ABSOLUTE_URI=/pma/
      - PMA_HOST=mysql
    networks:
      - webnet

  ftpd:
    image: garethflowers/ftp-server
    container_name: ftpd
    ports:
      - '20-21:20-21/tcp'
    volumes:
      - ./html:/home/wap
    environment:
      - FTP_USER=wap
      - FTP_PASS=5.cPfw_TUROTAxKW
      - PUBLICHOST=8.218.139.31

volumes:
  mysql-data:

networks:
  webnet:

