<?php
//顶部
$header = '<meta name="applicable-device" content="pc,mobile" /><meta itemprop="name" content="ContinuedMontenet：Treasure the soon-to-be-lost feature machine JAVA game software" /><meta name="KeyWords" content="Nokia, Sony Ericsson, nostalgic games, feature machine games, Symbian games, java games, java games Android emulator, Symbian games, java app store"><meta name="description" content="Mini World ☘️ Ah longContinuedMontenet Here you can download all the Saipan JAVA games recommended in Ah long s videos and live broadcasts, as well as an easy-to-use Android Saipan JAVA game simulator。">';
$title = "ContinuedMontenet：Treasure the soon-to-be-lost feature machine JAVA game software";
$title2 = "Java Store";
$exit = "exit";
//menu
$zhuye = "Home";
$sousuo = "search";
$juanzeng = "donation";
$user_login = "Log in";
$logouts = "Logout login";
//用户
$line = "on-line";
$lines = "off-line";
$more = "more";
$upload_games = "Upload game";
$upload_user = "Uploaded games";
$download_user = "Recently downloaded";
$ip_s = "IP territory";
$onine = "Online status";
$reg = "Registration date";
$download_nums = "Download Game";
$game_list = "Game list";
$comments_user = "Post comments";
$admin_user = "management function";
$group = "Member group";
$login_num = "Login history";
$avatars = "head portrait";
//首页
$covers240 = "screenshot";
$comments = "view";
$login_name = "I want to join";
$userss = "bit friends";
$update = "I want to upload";
$orders = "a new recording";
$tops = "TOP10";
$list = "list";
//games
$download_top = "most downloads";
$upload_new = "Latest upload";
$icons = "Icon";
$download_num = "download";
$number_num = "comments";
$pagerss = "page";
$pagerss1 = "Total";
$pagerss2 = "pages";
$pagers1 = "previous page";
$pagers2 = "next page";
$pagers_total = "Last page";
$upload_jar = "Upload jar";
$upload_game = "Upload SIS or N-Gage";
$filter = "Filter criteria";
$system_s = "system";
$who = "whole";
$res = "resolving power";
$cate = "type";
$act = "Action games";
$arpg = "Action role play";
$avg = "Adventure Games";
$etc = "Other games";
$fps = "First person shooting";
$ftg = "Fighting game";
$mug = "Music games";
$rac = "Racing Games";
$rpg = "cosplay";
$rts = "Immediate strategy";
$slg = "Strategic simulation";
$spg = "Sports games";
$stg = "Shooting game";
$app = "Application software";
$screen_s = "screen";
$djs = "Stand alone online";
$bs = "version";
$sizes = "capacity";
$yy =  "language";
$pt = "platform";
$fl = "categorize";
$cs = "manufacturer";
$apps = " the installation package";
//搜索
$keywords = "Search here……";
$search_name = "search result";
$search_top = "Recent hot searches";
//game
$comments1 = "viewpoint";
$comments_s = "View";
$comments_ss = "items";
$keywords_s = "Fill in here……";
$submits = "Submit";
$upload_screens = "Upload screenshot";
$games_s = "Same factory";
$games_ss = "similar";
$games_sss = "Congenial";
$edit = "edit";
$games_ssss = "brief introduction";
$port = "report";
//编辑
$edit_games = "Edit game profile";
$games_name = "Game name";
$cn = "Chinese name";
$platforms = "platform";
$game_autor = "provider";
$descr = "describe";
$oks = "determine";
$packages = "Installation package";
$cmd = "modify";
//低部
$info1 = "Disclaimer";
$info2 = "contact us";
$info3 = "Donate to us";
$info4 = "common problem";
$emulator = "simulator";
//链接
$local1 = "?local=en";
$local2 = "&local=en";

?>