<?php
//顶部
$header = '<meta itemprop="name" content="续梦网：珍藏即将遗失的诺基亚功能机JAVA游戏软件" /><meta name="description" itemprop="description" content="️啊龙童年游戏续梦网，这里可以下载啊龙视频和直播中推荐的所有塞班JAVA游戏，还有好用的安卓塞班JAVA游戏模拟器。" /><meta name="KeyWords" content="诺基亚,索尼爱立信,怀旧游戏,功能机游戏,塞班游戏,java游戏,java游戏安卓模拟器,啊龙童年游戏,塞班游戏,java应用商店">';
$title = "续梦网：珍藏即将遗失的功能机JAVA游戏软件";
$title2 = "续梦网";
$exit = "返回";
//menu
$zhuye = "首页";
$sousuo = "搜索";
$juanzeng = "捐赠";
$user_login = "登录";
//用户
$line = "在线";
$lines = "离线";
$more = "更多";
$upload_games = "上传游戏";
$upload_user = "上传的游戏";
$download_user = "最近下载";
$admin_user = "管理功能";
$ip_s = "IP属地";
$onine = "在线状态";
$reg = "注册日期";
$download_nums = "下载游戏";
$game_list = "游戏列表";
$comments_user = "发布评论";
$admin_user = "管理功能";
$logouts = "注销登录";
$group = "会员组";
$login_num = "登录历史";
$avatars = "头像";
//首页
$covers240 = "截图";
$comments = "玩家观点";
$login_name = "我要加入";
$userss = "位老铁";
$update = "我要上传";
$orders = "新收录";
$tops = "TOP10";
$list = "列表";
//games
$download_top = "最多下载";
$upload_new = "最新上传";
$icons = "图标";
$download_num = "下载";
$number_num = "评论";
$pagerss = "第";
$pagerss1 = "共";
$pagerss2 = "页";
$pagerss0 = "页";
$pagers1 = "上一页";
$pagers2 = "下一页";
$pagers_total = "尾页";
$upload_jar = "上传JAR";
$upload_game = "上传SIS或N-Gage";
$filter = "筛选条件";
$system_s = "系统";
$who = "全部";
$res = "分辨率";
$cate = "类型";
$act = "动作游戏";
$arpg = "动作角色扮演";
$avg = "冒险游戏";
$etc = "其他游戏";
$fps = "第一人称射击";
$ftg = "格斗游戏";
$mug = "音乐游戏";
$rac = "赛车游戏";
$rpg = "角色扮演";
$rts = "即时战略";
$slg = "战略模拟";
$spg = "体育游戏";
$stg = "射击游戏";
$app = "应用软件";
$screen_s = "筛选";
$djs = "单机联机";
$bs = "版本";
$sizes = "大小";
$yy =  "语言";
$pt = "平台";
$fl = "分类";
$cs = "厂商";
$apps = "安装包";
$ok = "打开";
//搜索
$keywords = "在这里搜索……";
$search_name = "搜索结果";
$search_top = "近期热搜";
//game
$comments1 = "观点";
$comments_s = "查看";
$comments_ss = "条";
$keywords_s = "这里填写内容……";
$submits = "提交";
$upload_screens = "上传截图";
$games_s = "同厂";
$games_ss = "同类";
$games_sss = "同好";
$edit = "编辑";
$games_ssss = "简介";
$port = "举报";
//编辑
$edit_games = "编辑游戏资料";
$games_name = "游戏名";
$cn = "中文名";
$platforms = "平台";
$game_autor = "提供商";
$descr = "描述";
$oks = "确定";
$packages = "安装包";
$cmd = "修改";
//低部
$info1 = "负责声明";
$info2 = "联系我们";
$info3 = "捐助我们";
$info4 = "常见问题";
$emulator = "模拟器";
?>