default.ini
emulation_accurate.ini
emulation_best_quality.ini
emulation_fastest.ini
picture_blackwhite.ini
picture_fix_trash.ini
picture_full_screen.ini
picture_full_size.ini
sound_full.ini
sound_simple.ini
